rango2/urls.py
from django.urls import path, re_path
from rango2 import views

app_name='rango2'
urlpatterns = [
    re_path('^$', views.index, name='index'),
    re_path('^about/', views.about, name='about'),
    re_path("^category/(?P<category_name_slug>[\w\-]+)/$", views.show_category, name='show_category'),
    re_path('^add_category/', views.add_category, name='add_category'),
    re_path('^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    re_path('^goto/', views.track_url, name='goto'),
    re_path('^register_profile/$', views.register_profile, name='register_profile'),
    re_path('^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    re_path('^like/$', views.like_category, name='like_category')
    # re_path('^register/', views.register, name='register'),
    # re_path('^login/', views.user_login, name='login'),
    # re_path('^logout/', views.user_logout, name='logout'),
]

tango_with_django_project2/urls.py
from django.contrib import admin
from django.urls import path, include, re_path, reverse
from rango2 import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango2:register_profile')


urlpatterns = [
    re_path('^$', views.index, name='index'),
    re_path('^wellspace/', include('rango2.urls')),
    path('admin/', admin.site.urls),
    re_path('^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    re_path('^accounts/', include('registration.backends.simple.urls'))  # 引入registration的URL映射
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango2/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(blank=True, unique=True)

    # 重写save（），保证name改变后，别名跟着一起改变
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'  # 重写name的复数形式

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango2/forms.py
from django import forms
from rango2.models import Page, Category, UserProfile
from django.contrib.auth.forms import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name', )  # 设定表单中包含哪些字段，这里何为可以不要views字段


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        fields = ('title', 'url', 'views')

    def clean(self):
        clean_data = self.cleaned_data
        url = clean_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            clean_data['url'] = url
            return clean_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())  # 使用这个小组件，密码不会直接渲染在HTML上

    class Meta:
        model = User
        fields = ('username', 'email', 'password')  # 表单显示的字段


class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango2/views.py
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from rango2.models import Category, Page, UserProfile
from rango2.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from datetime import datetime


# 主页视图
def index(request):
    request.session.set_test_cookie()
    context_dict = {}
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango2/index.html', context_dict)
    return response

    # return render(request, 'rango2/index.html', context_dict)


def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request, 'rango2/category.html', context_dict)


def add_category(request):
    form = CategoryForm()  # 创建一个类别表单对象

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            c = form.save(commit=True)
            print(c, c.slug)
            return index(request)
        else:
            print(form.errors)

    return render(request, 'rango2/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    return render(request, 'rango2/add_page.html', {'form': form, 'category': category})


@login_required
def register_profile(request):
    form = UserProfileForm()
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            return redirect('rango2:index')
        else:
            print(form.errors)
    contex_dict = {'form': form}
    return render(request, 'rango2/profile_registration.html', contex_dict)


@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('rango2:index')

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm(
        {'website': userprofile.website, 'picture': userprofile.picture}
    )

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango2:profile', user.username)
        else:
            print(form.errors)
    return render(request, 'rango2/profile.html', {'userprofile':userprofile, 'selecteduser': user, 'form':form})


def register(request):
    registered = False  # 模板是否注册成功
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)  # 和之前的form = CategoryForm(request.POST)有何区别？
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()  # 为什么之前的要page = form.save(commit=False)
            user.set_password(user.password)  # 计算密码哈希值，更新User对象
            user.save()

            profile = profile_form.save(commit=False)  # 因为要处理一对一的外键，所以False
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)  # 数据无效，在终端打印问题
    else:  # 如果不是POST请求，生成空表单，进行渲染
        user_form = UserForm()
        profile_form = UserProfileForm()

    context_dict = {}
    context_dict['user_form'] = user_form
    context_dict['profile_form'] = profile_form
    context_dict['registered'] = registered
    return render(request, 'rango2/register.html', context_dict)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('rango2:index'))
            else:
                return HttpResponse("Your Rango2 account is disabled.")
        else:
            # 提供的凭据有问题，用户名或者密码不正确
            print("Invalid login details:{0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango2/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango2:index'))


def about(request):
    return render(request, 'rango2/about.html', {})


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visits', str(datetime.now()))  # cookie是字符串
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')  # 所以自行转换为时间
    if (datetime.now() - last_visit_time).seconds > 0:
        visits = visits+1
        request.session['last_visits'] = str(datetime.now())
    else:
        request.session['last_visits'] = last_visit_cookie
    request.session['visits'] = visits


def track_url(request):
    page_id = None
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            page = Page.objects.get(id=page_id)
            if page:
                page.views = page.views + 1
                page.save()
                return HttpResponseRedirect(page.url)
    return HttpResponseRedirect(reverse('rango2:index'))


# 这是没有使用到ajax的局部刷新的方法，是刷新了整个页面的方法，不太友好
@login_required
def like_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        likes = 0
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                likes = cat.likes + 1
                cat.likes = likes
                cat.save()
    # return HttpResponseRedirect(reverse("rango2:show_category", kwargs={'category_name_slug': cat.slug}))
    return HttpResponse(likes)


@login_required
def like_category1(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        likes = 0
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                likes = cat.likes + 1
                cat.likes = likes
                cat.save()
            data = {'code': 200, 'hint': '操作成功'}
    return JsonResponse(data)


"""
# 客户端存储网站主页访问次数
def visitor_cookie_handler(request, response):
    visits = int(request.COOKIES.get('visits', '1'))
    last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))  # cookie是字符串
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')  # 所以自行转换为时间
    if (datetime.now() - last_visit_time).seconds > 0:
        visits = visits+1
        response.set_cookie('last_visit', str(datetime.now()))  # 如果该cookie不存在，会自动创建
    else:
        response.set_cookie('last_visit', str(datetime.now()))
    response.set_cookie('visits', visits)
"""

templates/rango2/about.html
{% extends 'rango2/base.html' %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    <img src="{{ MEDIA_URL }}cat.jpg"><br/>
    This tutorial has been put together by

    <button class="btn btn-primary"
    onclick="alert('You clicked the button using JavaScript.')">
        Click Me - I ran JavaScript
    </button>

    <button class="btn btn-primary"id="about-btn">
        Click Me - I'm JavaScript on Speed
    </button>

    <div id="msg">Hello - I'm here for a jQuery Example too</div>

    <p>This text is for jQuery Example</p>
{% endblock %}

templates/rango2/add_category.html
{% extends 'rango2/base.html' %}
{% load bootstrap_toolkit %}

{% block title_block %}
    Add Category
{% endblock %}

{% block body_block %}
 <form role="form"id="category_form"method="post"action="{% url 'rango2:add_category' %}">
     {% csrf_token %}
     {% for hidden in form.hidden_fields %}
     {{ hidden }}
     {% endfor %}
     {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br/>
        {{ field }}<br/>
     {% endfor %}
     <br/>
    <button class="btn btn-primary"type="submit"name="submit">Add Category</button>
 </form>


<!--
    <h1>Add a Category</h1>
    <div>
        <form id="category_form"method="post"action="{% url 'rango2:add_category' %}">
            {% csrf_token %}
            {{ form.as_p }}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit"name="submit"value="Create Category"/>
        </form>
    </div>
    -->
{% endblock %}

templates/rango2/add_page.html
{% extends 'rango2/base.html' %}

{% block title_block %}
    Add Page
{% endblock %}

{% block body_block %}
    {% if category %}
    <form role="form"id="page_form"method="post"action="{% url 'rango2:add_page' category.slug %}">
        <h2 class="form-signin-heading">
            Add a Page to<a href="{% url 'rango2:show_category' category.slug %}">{{category.name}}</a>
            {% csrf_token %}
        </h2>
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br/>
                {{ field }}<br/>
                <br/>
            {% endfor %}
            <!--{{ form.as_p }}-->
            <br/>
            <button class="btn btn-primary"type="submit"name="submit">Add Page</button>
    </form>
    {% else %}
        <p>This is category does not exist.</p>
    {% endif %}

<!--
<h1>Add a Page</h1>
    <div>
        <form id="page_form2"method="post"action="{% url 'rango2:add_page' category.slug %}">
            {% if category %}
            {% csrf_token %}

            {{ form.as_p }}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
                <br/>
            {% endfor %}
            {% else %}
                <strong>A category by this name does not exist</strong>
            {% endif %}
            <input type="submit"name="submit"value="Create Page"/>
        </form>
    </div>
-->

{% endblock %}

templates/rango2/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango2_template_tags %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v4-alpha.getbootstrap.com/favicon.ico">

    <title>
        Well space-
        {% block title_block %}
            How to Tango with Django!!！
        {% endblock %}
    </title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Well space</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rango2:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'rango2:about' %}">About</a>
          </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango2/">Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango2:add_category' %}">Add a New Category</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango2:profile' user.username %}">Profile</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'registration_register' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
            </li>
            {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="#">Help</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
            {% block body_block %}

            {% endblock %}
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/rango2-jquery.js' %}"></script>
    <script src="{% static 'js/rango2-ajax.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/rango2/base_bootstrap.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v4-alpha.getbootstrap.com/favicon.ico">

    <title>
        Rango2-
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Rango2</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rango2:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'rango2:about' %}">About</a>
          </li>
            {% if user.is_anthenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango2/">Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango2:add_category' %}">Add a New Category</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'registration_register' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="auth_login">Login</a>
            </li>
            {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="#">Help</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
            {% block body_block %}

            {% endblock %}
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/rango2/base_copy.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango2_template_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Rango2-
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
</head>

<body>
    <div>
        {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
    </div>

    <div>
        {% block body_block %}
        {% endblock %}
    </div>
    <hr/>
    <div>
        <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango2:add_category' %}">Add New Category</a></li>
                <li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
                <li><a href="{% url 'auth_logout' %}?next=/rango2/">Logout</a></li>
            {% else %}
                <li><a href="{% url 'registration_register' %}">Register</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
                <li><a href="{% url 'rango2:about' %}">About</a></li>
                <li><a href="{% url 'rango2:index' %}">Index</a></li>
        </ul>
    </div>

</body>

</html>

templates/rango2/category.html
{% extends 'rango2/base.html' %}
{% load staticfiles %}

{% block title_block %}
{{category.name}}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{category.name}}</h1>
        <div>
            <strong id="like_count">{{ category.likes }}</strong> people like this category.
            {% if user.is_authenticated %}
                <button id="likes"data-catid="{{category.id}}"
                        class="btn btn-primary btn-sm"type="button">Like</button>
            {% else %}
            {% endif %}
        </div>

        {% if pages %}
        <ul>
            {% for page in pages %}
                <li><a href="{% url 'rango2:goto' %}?page_id={{page.id}}">{{page.title}}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'rango2:add_page' category.slug %}">Add a page.</a>
        {% endif %}

    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

templates/rango2/cats.html
<ul>
    {% if cats %}
        {% for cat in cats %}
            {% if cat == act_cat %}
            <li>
                <strong><a href="{% url 'rango2:show_category' cat.slug %}">{{ cat.name }}</a></strong>
            </li>
            {% else %}
            <li>
                <a href="{% url 'rango2:show_category' cat.slug %}">{{ cat.name }}</a>
            </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango2/index.html
{% extends 'rango2/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Index
{% endblock %}

{% block body_block %}
<div class="jumbotron">
    <h1>Well space says...</h1>
    {% if user.is_authenticated %}
        howdy :{{ user.username }}
    {% else %}
        hey there partner!
    {% endif %}
</div>

    <div class="row markting">
        <div class="col-lg-6">
            <h4>Most Liked Categories</h4>
            <p>
                {% if categories %}
                    <ul class="list-group">
                    {% for category in categories %}
                    <li class="list-group-item"><a href="{% url 'rango2:show_category' category.slug %}">{{category.name}}</a></li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <strong>There are no categories present.</strong>
                {% endif %}
            </p>
        </div>

        <div class="col-lg-6">
            <h4>Most Viewed Pages</h4>
            <p>
                {% if pages %}
                <ul class="list-group">
                {% for page in pages %}
                    <li class="list-group-item"><a href="{{page.url}}">{{page.title}}</a></li>
                {% endfor %}
                </ul>
                {% else %}
                    <strong>There are no pages present.</strong>
                {% endif %}
            </p>
        </div>
    </div>
        <img src="{% static 'images/rango2.jpg' %}" alt="Picture of Rango2">
{% endblock %}